services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: docker/rtype_jenkins:latest
    container_name: rtype_jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8081:8082"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rtype_ci_network

volumes:
  jenkins_home:
    name: rtype_jenkins_home

networks:
  rtype_ci_network:
    driver: bridge
    name: rtype_ci_network
